// Generated by CoffeeScript 1.10.0
(function () {
  module.exports = function (robot) {
    return robot.hear(/test-hubot (.*)/i, function (res) {
      var message = res.match[1];

      doGET(message).then(function (response) {
        if(response) {
            if(response.status == "success"){
                return res.send(response.message);
            }

        }
      });

    });
  };

}).call(this);


var baseUrl = 'http://localhost:9000';
var timeout = 15000;

var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;

function doGET(question) {

  return new Promise(function (resolve, reject) {

    var url = baseUrl + '/question=' + question;
    var xhr = new XMLHttpRequest(url);
    xhr.open("GET", url, true);

    xhr.timeout = timeout;
    xhr.ontimeout = function () {
      console.log("Request to ", url, "timed out.")
    };

    xhr.onload = function (e) {
      if (xhr.readyState === 4) {
        if (xhr.status === 200) {
          resolve(JSON.parse(xhr.responseText));
        } else {
          reject(xhr.statusText);
        }
      }
    };

    xhr.onerror = function (e) {
      console.error(xhr.statusText);
    };
    xhr.send();
  });
}
