// Generated by CoffeeScript 1.10.0
(function () {
  module.exports = function (robot) {
    return robot.hear(/test-hubot (.*)/i, function (res) {
      var message = res.match[1];

      httpRequest().doGET(message).then(function (response) {
        if (response) {
          return res.send(response.answer);
        }
      });

    });
  };

}).call(this);

///


var httpRequest = function () {

  var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;

  function doGET(question) {

    return new Promise(function (resolve, reject) {

      var url = getBaseUrl() + '/question=' + question;
      var xhr = new XMLHttpRequest(url);
      xhr.open("GET", url, true);

      xhr.timeout = getTimeout();
      xhr.ontimeout = function () {
        console.log("Request to ", url, "timed out.")
      };

      xhr.onload = function (e) {
        if (xhr.readyState === 4) {
          if (xhr.status === 200) {
            resolve(JSON.parse(xhr.responseText));
          } else {
            reject(xhr.statusText);
          }
        }
      };

      xhr.onerror = function (e) {
        console.error(xhr.statusText);
      };
      xhr.send();
    });
  }

  function getBaseUrl() {
    return 'http://localhost:9000';
  }

  function getTimeout() {
    return 15000;
  }

  return {
    doGET: doGET
  }
};

